### ISSUE TITLE
No module named 'scipy'

### ISSUE THREAD

**Issue by dham-eng** [looooo/freecad.frametools#4]
Hello,

while trying to run Frame and Beams Workbench on FreeCAD 0.18, it gave me an "No module named 'scipy'" error, throwing this in the report window:

```
No module named 'scipy'
Traceback (most recent call last):
  File "C:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\frame\freecad\frametools\init_gui.py", line 24, in Initialize
    from freecad.frametools import commands
  File "C:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\frame\freecad\frametools\commands.py", line 7, in <module>
    from . import fem2d
  File "C:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\frame\freecad\frametools\fem2d.py", line 5, in <module>
    from scipy import sparse
```

Thank you in advance!

**Comment by luzpaz** [comment]
@looooo is the solution as easy as `pip3 install scipy` ?

**Comment by looooo** [comment]
Depends on the freecad build. If installed via system package-manager scipy should be installed this way. If conda based appimage is used, scipy should be included. So yes, somehow scipy must be installed. I close this for now as this is not an issue of this workbench.
