### ISSUE TITLE
missing yaml library : AppImage version of FC

### ISSUE THREAD

**Issue by oddtopus** [looooo/freecad.frametools#6]
I wonder if the following error is due because the AppImage is not able to get the system's environment of Python3.
Suggestions howto patch or skip this dependency?

Init: Entering event loop
Init: Processing command line files
No module named 'yaml'
Traceback (most recent call last):
  File "/home/user/.FreeCAD/Mod/frame/freecad/frametools/init_gui.py", line 24, in Initialize
    from freecad.frametools import commands
  File "/home/user/.FreeCAD/Mod/frame/freecad/frametools/commands.py", line 7, in <module>
    from . import fem2d
  File "/home/user/.FreeCAD/Mod/frame/freecad/frametools/fem2d.py", line 9, in <module>
    import yaml

**Comment by looooo** [comment]
yaml should be included in the appimage. Which version of FreeCAD are you using?

**Comment by oddtopus** [comment]
OS: Linux Mint 19
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16121 (Git) AppImage
Build type: Release
Branch: master
Hash: a7919b63dea4bb1f1107c80ed44758479eec3d8d
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Italian/Italy (it_IT)

Also yaml exist in my OS because when I import yaml from the python3
console I get no error but when I do the same from the console of the
appimage:

>>> import yaml
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'yaml'

Maybe there's an alias in the environment of FreeCAD?


Il giorno mer 16 ott 2019 alle ore 09:06 lorenz <notifications@github.com>
ha scritto:
